#!/usr/bin/env python3
"""Enroll a gallery of face images into ZepIris.

Each image becomes one enrolled person whose name is the file's stem:
    gallery/alice.jpg   -> person "alice"
    gallery/bob_k.png   -> person "bob_k"

Images are enrolled via the running API's POST /v1/faces/upsert (so re-running
updates rather than erroring on duplicates).

If the gallery folder is empty or missing, a fallback set of individual faces is
generated by cropping the sample group photo bundled with InsightFace, so the
demo always has someone to match against.

Prerequisites:
    - API running (default http://localhost:8000)
    - ML inference service running and reachable by the API
    - (fallback only) insightface + opencv installed

Usage:
    python scripts/seed_gallery.py
    python scripts/seed_gallery.py --gallery ./gallery --api http://localhost:8000
    python scripts/seed_gallery.py --tenant default
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import requests

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}


def _enroll(api: str, tenant: str, person_id: str, image_path: Path) -> tuple[bool, str]:
    """Upsert one image. Returns (ok, message)."""
    url = f"{api.rstrip('/')}/v1/faces/upsert"
    with image_path.open("rb") as fh:
        files = {"file": (image_path.name, fh, "image/jpeg")}
        data = {"id": person_id, "tenant": tenant}
        try:
            resp = requests.post(url, data=data, files=files, timeout=60)
        except requests.RequestException as exc:
            return False, f"request failed: {exc}"

    if resp.status_code == 200:
        return True, "enrolled"
    try:
        detail = resp.json().get("detail", resp.text)
    except ValueError:
        detail = resp.text
    if isinstance(detail, dict):
        detail = detail.get("message", detail)
    return False, f"HTTP {resp.status_code}: {detail}"


def _make_fallback_gallery(gallery_dir: Path) -> list[Path]:
    """Crop individual faces from InsightFace's bundled sample photo."""
    try:
        import cv2
        from insightface.app import FaceAnalysis
        from insightface.data import get_image
    except Exception as exc:  # pragma: no cover - depends on optional ml deps
        print(f"  ! Cannot build fallback gallery (ml deps missing): {exc}")
        return []

    print("  · Gallery empty — generating fallback faces from InsightFace sample…")
    img = get_image("t1")  # BGR group photo
    app = FaceAnalysis(name="buffalo_l")
    app.prepare(ctx_id=-1, det_size=(640, 640))
    faces = app.get(img)
    faces = sorted(faces, key=lambda f: float(f.bbox[0]))  # left-to-right => stable names

    gallery_dir.mkdir(parents=True, exist_ok=True)
    h, w = img.shape[:2]
    created: list[Path] = []
    for i, face in enumerate(faces, start=1):
        x1, y1, x2, y2 = (int(v) for v in face.bbox[:4])
        # generous margin so the saved photo isn't a tight crop
        mw, mh = int((x2 - x1) * 0.5), int((y2 - y1) * 0.6)
        x1, y1 = max(0, x1 - mw), max(0, y1 - mh)
        x2, y2 = min(w, x2 + mw), min(h, y2 + mh)
        crop = img[y1:y2, x1:x2]
        out = gallery_dir / f"person-{i}.jpg"
        cv2.imwrite(str(out), crop)
        created.append(out)
    print(f"  · Created {len(created)} fallback face image(s) in {gallery_dir}")
    return created


def main() -> int:
    parser = argparse.ArgumentParser(description="Seed the ZepIris face gallery.")
    parser.add_argument("--gallery", default="gallery", help="Folder of person images")
    parser.add_argument("--api", default="http://localhost:8000", help="ZepIris API base URL")
    parser.add_argument("--tenant", default="default", help="Tenant to enroll under")
    args = parser.parse_args()

    gallery_dir = Path(args.gallery)
    images = (
        sorted(p for p in gallery_dir.iterdir() if p.suffix.lower() in IMAGE_EXTS)
        if gallery_dir.is_dir()
        else []
    )

    if not images:
        images = _make_fallback_gallery(gallery_dir)
    if not images:
        print("No images to enroll. Add files to the gallery/ folder and retry.")
        return 1

    print(f"Enrolling {len(images)} image(s) into {args.api} (tenant={args.tenant})…\n")
    enrolled = 0
    failures = 0
    for path in images:
        person_id = path.stem
        ok, msg = _enroll(args.api, args.tenant, person_id, path)
        mark = "✓" if ok else "✗"
        print(f"  {mark} {person_id:<20} {msg}")
        if ok:
            enrolled += 1
        else:
            failures += 1

    print(f"\nDone. Enrolled {enrolled}, failed {failures}.")
    return 0 if failures == 0 else 2


if __name__ == "__main__":
    sys.exit(main())
